basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: My API
  version: "1.0"
paths:
  /task:
    post:
      description: Create and run in progress task from user, by "image" and "filter"
      parameters:
      - description: Value
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: TaskUuid
          schema:
            type: string
        "400":
          description: Missing key
          schema:
            type: string
        "405":
          description: Failed to create task
          schema:
            type: string
      summary: Create and run in progress task
swagger: "2.0"
